/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_biblioteca;



/**
 *
 * @author FARRICO
 */
public class MainWind extends javax.swing.JFrame {
    
    CRUD_Metodo db = new CRUD_Metodo();
    
    /**
     * Creates new form MainWind
     */
    public MainWind() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DB_Conect = new javax.swing.JButton();
        DB_RLector = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        DB_ConsultLector = new javax.swing.JButton();
        DB_ModificarLector = new javax.swing.JButton();
        DB_DeleteLector = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DB_Conect.setText("Conectar a Base de Datos");
        DB_Conect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DB_ConectActionPerformed(evt);
            }
        });

        DB_RLector.setText("Registrar Datos de Usuario");
        DB_RLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DB_RLectorActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        DB_ConsultLector.setText("Consultar Datos de Usuario");
        DB_ConsultLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DB_ConsultLectorActionPerformed(evt);
            }
        });

        DB_ModificarLector.setText("Modificar Datos de Usuario");
        DB_ModificarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DB_ModificarLectorActionPerformed(evt);
            }
        });

        DB_DeleteLector.setText("Borrar Datos de Usuario");
        DB_DeleteLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DB_DeleteLectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DB_RLector, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DB_Conect, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DB_ConsultLector, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DB_ModificarLector, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DB_DeleteLector, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(DB_Conect, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DB_RLector, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DB_ConsultLector, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DB_ModificarLector, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DB_DeleteLector, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salir)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        DB_RLector.setEnabled(false);
        DB_ConsultLector.setEnabled(false);
        DB_ModificarLector.setEnabled(false);
        DB_DeleteLector.setEnabled(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void DB_ConectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DB_ConectActionPerformed
        
        db.MySQLConnection("root", "", "bibliov2");
        if(db.Co==0){
        DB_Conect.setEnabled(false);
        DB_RLector.setEnabled(true);
        DB_ConsultLector.setEnabled(true);
        DB_DeleteLector.setEnabled(true);
        DB_ModificarLector.setEnabled(true);
        }
        db.closeConnection();
    }//GEN-LAST:event_DB_ConectActionPerformed

    private void DB_RLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DB_RLectorActionPerformed
        RegisterWind wr = new RegisterWind(new javax.swing.JFrame(), true);
        wr.setLocationRelativeTo(null);
        wr.setVisible(true);
    }//GEN-LAST:event_DB_RLectorActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void DB_ConsultLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DB_ConsultLectorActionPerformed
        ConsultWind wr = new ConsultWind(new javax.swing.JFrame(),true);
        wr.setLocationRelativeTo(null);
        wr.setVisible(true);
    }//GEN-LAST:event_DB_ConsultLectorActionPerformed

    private void DB_ModificarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DB_ModificarLectorActionPerformed
        UpdateWind wr = new UpdateWind(new javax.swing.JFrame(),true);
        wr.setLocationRelativeTo(null);
        wr.setVisible(true);
    }//GEN-LAST:event_DB_ModificarLectorActionPerformed

    private void DB_DeleteLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DB_DeleteLectorActionPerformed
        DeleteWind wr= new DeleteWind(new javax.swing.JFrame(),true);
        wr.setLocationRelativeTo(null);
        wr.setVisible(true);


    }//GEN-LAST:event_DB_DeleteLectorActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DB_Conect;
    public javax.swing.JButton DB_ConsultLector;
    private javax.swing.JButton DB_DeleteLector;
    private javax.swing.JButton DB_ModificarLector;
    private javax.swing.JButton DB_RLector;
    private javax.swing.JButton Salir;
    // End of variables declaration//GEN-END:variables
}
